<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        
        <!-- 添加程序集版本信息 -->
        <AssemblyVersion>1.4.4.0</AssemblyVersion>
        <FileVersion>1.4.4.0</FileVersion>
        <Version>1.4.4</Version>
        <Authors>Masaicker, YurisCat</Authors>
        <Company>YMC_MHZ</Company>
        <Product>MoreHead</Product>
        <Description>一个简单好玩的装饰模组，提供unitypackage，供玩家自行导入模型。</Description>
        <Copyright>Copyright © 2026</Copyright>
        <PackageProjectUrl>https://github.com/Masaicker/repo-MoreHead</PackageProjectUrl>
        
        <!-- 调试设置 -->
        <DebugType>portable</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <PropertyGroup>
        <RepoPath Condition="'$(RepoPath)' == ''">C:\Program Files (x86)\Steam\steamapps\common\REPO\REPO_Data\Managed\</RepoPath>
        <BepInExPath Condition="'$(BepInExPath)' == ''">C:\Users\Joao\AppData\Roaming\Thunderstore Mod Manager\DataFolder\REPO\profiles\Default\BepInEx\core\</BepInExPath>
        <MenuLibPath Condition="'$(MenuLibPath)' == ''">C:\Users\Joao\AppData\Roaming\Thunderstore Mod Manager\DataFolder\REPO\profiles\Default\BepInEx\plugins\nickklmao-MenuLib\</MenuLibPath>
        <BCEPath Condition="'$(BCEPath)' == ''">C:\Users\Joao\AppData\Roaming\Thunderstore Mod Manager\DataFolder\REPO\profiles\NewMoreHead\BepInEx\plugins\innominata-BepInEx_Console_Extensions-2.0.0\</BCEPath>
        <SubPath Condition="'$(SubPath)' == ''" />
    </PropertyGroup>

    
    <ItemGroup>
        <Reference Include="$(RepoPath)$(SubPath)*Unity*" Private="false" />
        <Reference Include="$(RepoPath)$(SubPath)Assembly-CSharp*" Private="false" />
        <Reference Include="$(RepoPath)$(SubPath)Newtonsoft*" Private="false" />
        <Reference Include="$(RepoPath)$(SubPath)Photon*" Private="false" />
        <Reference Include="$(RepoPath)$(SubPath)*Steamworks*" Private="false" />
        <Reference Include="$(RepoPath)$(SubPath)System.dll" Private="false" />
        <Reference Include="$(BepInExPath)BepInEx.dll" Private="false" />
        <Reference Include="$(BepInExPath)0Harmony.dll" Private="false" />
        <Reference Include="$(MenuLibPath)MenuLib.dll" Private="false" />
        <Reference Include="$(BCEPath)BCE.dll" Private="false" />
    </ItemGroup>

</Project>
